# python1

On reprend ici les exemples de morceaux de code donnés dans python1.pdf

## Aide de fonctions
Pour obtenir l'aide d'une fonction python en utilisant ipython ou jupyter - exemple pour la fonction zip

In [1]:
? zip

Init signature:  zip(self, /, *args, **kwargs)
Docstring:     
zip(*iterables, strict=False) --> Yield tuples until an input is exhausted.

   >>> list(zip('abcdefg', range(3), range(4)))
   [('a', 0, 0), ('b', 1, 1), ('c', 2, 2)]

The zip object yields n-length tuples, where n is the number of iterables
passed as positional arguments to zip().  The i-th element in every tuple
comes from the i-th iterable argument to zip().  This continues until the
shortest argument is exhausted.

If strict is true and one of the arguments is exhausted before the others,
raise a ValueError.
Type:           type
Subclasses:     

## Affectation de variables

On peut définir plusieurs variables en même temps en utilisant ',', le typage est implicite.

In [154]:
k=4  ; c = 5*k
# équivalent à :
# k = 4
# c = 5*k 
print(c)

20


Le ";" permet de séparer deux instructions distinctes sur la même ligne.

In [155]:
a=5 ; b=5. ; c =14.1 
print(type(a),type(b),type(c))

<class 'int'> <class 'float'> <class 'float'>


In [2]:
a= 3!=3
print(a)

False


## Affichage de variables

L'instruction print permet d'afficher le contenu d'une variable, quel que soit son type.

In [3]:
d=12*10
print(d)

120


Avec ipython3, jupyter ou la console, écrire le nom de la variable permet d'afficher sa valeur si aucune autre instruction ne vient après.

In [ ]:
d  #affiche la valeur de d (ne fonctionnerait pas depuis l'éditeur de script)

In [156]:
d 
a=4

In [4]:
a=1 ; b=2 
a ; b  

2

Quand on définit une variable, sa valeur n'est pas affichée, il n'y a pas d'écho.

In [ ]:
e=-17 # pas d'écho

## Opérateurs

On a les opérateurs habituels d'addition, soustraction, multiplication et division.
Signalons quelques opérateurs spécifiques.
* L'opérateur modulo : %

In [ ]:
66%5

* L'opérateur quotient de division entière : //

In [ ]:
59//4

* L'opérateur d'élévation à la puissance : **

In [ ]:
2**5

* Les opérateurs de comparaison : ==, !=, <,>,<=,>=

In [ ]:
print(8/4==2) ; print(2!=4)

In [ ]:
print(4<=4, 4>4)

* L'opérateur logique "et" : & (ou and)

In [6]:
a = 12
(a > 1) and (a<= 17) 

True

* L'opérateur logique "ou" : | (ou or)

In [7]:
(a <= 7) or (a> 15)


False

* L'opérateur de négation not

In [8]:
not(a<11)

True

## Chaînes de caractères

On peut utiliser des guillemets ou des simples quotes

In [ ]:
print("Hello")   
print('Bonjour ')

On peut faire afficher un simple quote dans une chaîne de caractères

In [ ]:
print("il n'y a personne") 

Concaténation de chaînes de caractères

In [9]:
L="le temps"+" ne fait rien à l'affaire"  #Penser à introduire les espaces entre les chaines concaténées si nécessaire
print(L)

le temps ne fait rien à l'affaire


In [10]:
print(10*"panier piano ")

panier piano panier piano panier piano panier piano panier piano panier piano panier piano panier piano panier piano panier piano 


In [11]:
print("Bienvenue en M"+str(31%5))

Bienvenue en M1


In [ ]:
print("Bienvenue en M"+1)

Quelques exemples de méthodes

In [12]:
s = "Ce cours est passionant !"
print(s)
print(s.find("o"))    # position de la première occurance                                  
print(s.split()) 
print(s.count("m")) # nombre d'occurences

Ce cours est passionant !
4
['Ce', 'cours', 'est', 'passionant', '!']
0


In [14]:
print(s.replace("passionant", "affligeant"))

Ce cours est affligeant !


In [13]:
print(s) 

Ce cours est passionant !


Taille d'une chaîne de caractères

In [15]:
len(s)

25

## Les listes

In [18]:
l1 = [1, 4, 5, 1]; print(l1) 
l1.pop()
print(l1)

[1, 4, 5, 1]
[1, 4, 5]


In [19]:
l2 = ['maths', 'M', 1, '2023']; print(l2) # mixte  

['maths', 'M', 1, '2023']


In [20]:
l1 + l2   

[1, 4, 5, 'maths', 'M', 1, '2023']

In [21]:
l1*3 #affiche l1*3 sans modifier l1

[1, 4, 5, 1, 4, 5, 1, 4, 5]

In [ ]:
l1=l1*2
l1

In [ ]:
l1[:]  

In [ ]:
l = [1, 3, 5, 'abc', 'efg', 17, -4, 5.5, -2.1, 'rstu', 14, 15, 16, 'z']

In [ ]:
l[0] 

In [ ]:
l[0:2]  

In [ ]:
l[-1]  

In [ ]:
l[-2]  

In [ ]:
l[2:-1] 

In [ ]:
l[2:] 

In [ ]:
l[2:9:3]

In [ ]:
l[2:8:3]

In [ ]:
l[8:2:-2]

In [ ]:
l1 = [1, 5]                                                                     
l2 = l1                                                                         
l1[0]=6                                                               
print(l2); print(l1) 

In [ ]:
id(l1)==id(l2) #id(objet) = identifiant unique de l'objet

In [ ]:
l6=[6,5]
print(l1==l6) 
print(id(l1)==id(l6)) #l1 et l6 ont un contenu identique mais sont deux objets distincts et indépendants.

In [ ]:
l1 = [1, 5]; 
l2 = 1*l1;
l3 = l1.copy()
l4= l1[:]
l1.append(6)
print(l1, l2, l3, l4)  

In [ ]:
a="Abracadrabra"; 
b=a.replace("a","o")
print(b)

In [ ]:
print(a)

In [ ]:
a=a+"dabradabradabra" 
print(a)
# Contrairement à ce qu'on pourrait croire, on n'a pas modifié l'objet auquel était associé la variable a. 
# On a créé un nouvel objet, auquel on donne le nom a, écrasant ainsi l'ancienne variable a. 
# Pour s’en convaincre, on peut utiliser la fonction id().

## Les tuples

In [23]:
t = (5, 8, 9, 'abcd') 

In [24]:
print(t[1]); print(t[3]) 

8
abcd


In [25]:
t1 = tuple([4, 'eeee', 9, 10]) 
print(t1)

(4, 'eeee', 9, 10)


In [26]:
t1.count(10)

1

In [ ]:
print(id(t1))
t1 = t1 + t; print(t1)
print(id(t1)) 

In [ ]:
t1 = tuple([4, 'eeee', 9, 10]) 
t1 = 4*t1; 
print(t1)

## Fonctions sum et len

In [ ]:
t1 = tuple([4.,  9, 10]) 
len(t1)        

In [ ]:
sum(t1)        

## Les sets

In [27]:
s1 = {4, 3, 1, 2, 2, 1}
print(s1)  
s2 = {4, 2, 1, 3} # autre style de definition
s1 == s2

{1, 2, 3, 4}


True

## Les dictionnaires

In [29]:
dpt = {'Isere': 38, 'Drome': 26, 'Bouches-du-Rhone': 13, 'Finistere': 29 } 

In [33]:
dpt[2] 

KeyError: 2

In [31]:
dpt.keys() 

dict_keys(['Isere', 'Drome', 'Bouches-du-Rhone', 'Finistere'])

In [32]:
dpt.values()

dict_values([38, 26, 13, 29])

## range

In [ ]:
a = range(10)  
for j in a:
    print(j)

In [ ]:
b = range(2, 17, 3)   
for j in b:
    print(j)

In [ ]:
c = range(2, 18, 3)
for j in c:
    print(j)    

## Boucle for 

In [ ]:
for i in range(4):                                                             
    print(i)
print("et voilà !")

In [ ]:
l = ['ABCD', 'FG', 'WXY']
for mot in l:
    print(mot)


## Boucle while

In [ ]:
i= 0                                                                            
while i<5:                                                                     
    print(i)                                                                    
    i = i + 1  

## if

In [ ]:
i = 1                                                                          
if (i==0):                                                                      
    print('zero')                                                                                                                            
else:                                                                           
    print('Non nul') 

In [ ]:
i = 3                                                                         
if (i==0):                                                                      
    print('zero')                                                               
elif (i==2):                                                                    
    print('deux')                                                               
else:                                                                           
    print('Ni 0, ni 2') 

## Les fonctions 

In [ ]:
def g(t):                                                                       
    return t**2 + 1 

a=g(3)
type(g)
g(np.linspace())

In [ ]:
f = lambda t: t**2 + 1                                                           
print(f(3))   
type(f)

In [ ]:
def g(t=5):
    return t**2 + 1
print(g())
print(g(2))

## Le module math 

In [ ]:
log(17)

In [ ]:
from math import sqrt, pi, sin                                                  
print([sqrt(73), sin(7*pi/2.)])  

In [ ]:
import math                                                                     
print(math.log(17))

In [ ]:
import math as m                                                                
deuxpi = 2 * m.pi   *m.log(17)

In [ ]:
from math import sqrt, pi                                   
print(sqrt(5*pi))                                                               
#print(log(16)) 
#print(math.log(16)) 

In [ ]:
from math import *
print(log(16)) 
#print(math.log(16)) 

# numpy

## Fonctions mathématiques dans numpy

Avec numpy, on peut importer les fonctions du module math de python. On peut les utiliser sur des tableaux numpy.

In [ ]:
from numpy import sqrt, pi, sin                                          
[sqrt(e), sin(7*pi/2.)]

## Tableaux numpy 1D (numpy.array 1D)

Exemple d'un tableau numpy unidimensionnel à 3 éléments

In [36]:
import numpy as np                                                              
t = np.array([np.pi/4, np.pi/2, np.pi])
print(t)

[0.78539816 1.57079633 3.14159265]


### Manipulations algébrique

In [37]:
print(np.sin(t))

[7.07106781e-01 1.00000000e+00 1.22464680e-16]


In [38]:
print(3*t) ; print(t+np.array([1,2,3])) 

[2.35619449 4.71238898 9.42477796]
[1.78539816 3.57079633 6.14159265]


### Accès aux éléments d'un array 1-D

In [ ]:
t[0]   

In [ ]:
t[[1,2,0]]  

Un tableau numpy possède des attributs (shape, size, ...) et des méthodes (sum, sort, ...)

In [ ]:
t.shape  

In [ ]:
t.size  

In [39]:
t.sum()  

5.497787143782138

In [ ]:
t.sort() 
t

In [ ]:
t[0:2]  

In [ ]:
t[-1]  

In [ ]:
t[1:]    

Attention au typage d'un array

In [ ]:
t1 = np.array([1.0,2,3])  
print(type(t1[2]))
print(t1) 

In [ ]:
t1 = np.array([1,2,3])  
print(t1) 
t1[1]=8.7 # t1 est un tableau d'entiers, le float 8.7 est converti en entier !
type(t1[1])
print(t1) 


In [ ]:
t2 = np.array([1,"deux",3]) 
print(t2)


## numpy.arange 

numpy.arange ressemble à range mais est plus général. Permet de définir des suites de valeurs numériques avec des pas quelconques (pas forcément entiers)

In [ ]:
t = np.arange(5); print(t) 

In [ ]:
t = np.arange(12, 16); print(t)

In [ ]:
t = np.arange(2, 14, 4); print(t) 

In [ ]:
t = np.arange(1, 1.9, 0.1); print(t)  

In [ ]:
print(np.arange(1.25, 0.25))

## numpy.linspace

Comme numpy.arange,  permet de créer des discrétisations mais cette fois en spécifiant le nombre d'éléments. A la différence de numpy.arange, le deuxième argument est inclus dans la discrétisation.

In [ ]:
t = np.linspace(3, 4, 5); print(type(t))  

## numpy et les tableaux multidimensionnels 

Voici un exemple de matrice 2x2 (2 lignes et 2 colonnes)

In [ ]:
M1 = np.array([[1.0,2,3],[4,5,6],[7,8,9]]) # matrice 3x3 de floats (car M[1,1] est un float)
print(M1) 

Un exemple de matrice 4x2 (4 lignes et 2 colonnes)

In [ ]:
M2 = np.array([[21,22],[23,24],[33,34],[-13,-14]])
print(M2) # matrice  4x2

In [ ]:
print(M2.T) #ou print(np.transpose(M2))

Pour accéder à un élément d'une matrice, on utilise les crochets (la numérotation commence à 0 en python)

In [ ]:
M2[0,1] 

Pour accéder à la 3ème ligne de M2 (d'indice 2), on peut faire de deux manières différentes:

In [ ]:
M2[2,:]
M2[2,]

Pour accéder à la  1ère colonne de M2 (indice 0), on fait :

In [ ]:
M2[:,0]

Pour accéder aux lignes d'indices 1 et 3 de M2, on fait:

In [ ]:
M2[[1,3],:]  # M2[(1,3),:] marche aussi

Soit la matrice 3x3 M3 suivante

In [ ]:
M3=np.array([[1,4,-5],[7,0,-3],[6,-4,2]]); print(M3)

Pour récupérer le bloc [ [1,4],[6,-4] ] on peut faire 

In [ ]:
M3[[0,2],:][:,[0,1]]

numpy permet de manipuler d'autres objets mathématiques que les matrices.
Voici un exemple de tenseur 2x2x2

In [ ]:
P = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]); print(P) 
print(P[0,1,0]) #profondeur, puis ligne, puis colonne

## La fonction numpy.sum (ou la méthode équivalente t.sum)

In [ ]:
t = np.array([[0, 4, 2],[3, 1, 6]])

In [ ]:
print(np.sum(t)) # la fonction du package numpy

# ou de façon équivalente
print(t.sum()) # La  méthode sum du type numpy.array (voir plus tard) 

In [ ]:
np.sum(t,0)
#t.sum(0)

In [ ]:
np.sum(t,1) 
#t.sum(1)

## Initialisation de tableaux 

In [ ]:
d1 = np.zeros((2,2,2)); print(d1)
print() 
d2 = np.ones((3,3)); print(d2)
print()
d3 = np.eye(3); print(d3)
print()
d4 = np.eye(4,k=-1); print(d4)
print()
V=np.array([1,3,2,7])
d5 = np.diag(V,k=-1); print(d5)
print()


## numpy.shape et numpy.size

Pour récupérer la taille sous forme de tuple et le nombre d'éléments d'un tableau numpy

In [ ]:
t = np.array([[1, 2, 3],[4, 5, 6]])
np.shape(t)

In [ ]:
t.shape

In [ ]:
print(np.size(t))
#print(t.size) # autre possibilité équivalente, via la méthode size

Pour obtenir le nombre de lignes et le nombre de colonnes de t (possible aussi avec np.shape)

In [ ]:
[np.size(t,0), np.size(t,1)]                                   

## Manipulations de tableaux numpy 

In [ ]:
a = np.array([5, 7, 6, 5, 6, 2, 1, 13, 11])
at = np.sort(a) #fonction np.sort : renvoie un array des éléments de a triés par ordre croissant (sans modification de a)
print(at)

In [ ]:
print(a);
a.sort() # methode sort : tri de a avec modification de a (objet mutable). 
print(a)

In [ ]:
au = np.unique(a) # suppression des doublons (sans modifier a)
print(au)

In [ ]:
b = np.append(au, np.array([-12, -10])); print(b)

## Les fonctions statistiques de numpy

In [ ]:
a = np.array([12, 14, 35, 22])
[np.mean(a), np.var(a), np.std(a), np.median(a)]

## numpy par rapport aux listes et aux tuples

On peut utiliser des fonctions de numpy sur des listes ou des tuples.

In [ ]:
L = [4, 5, 6]                                                      
print(np.mean(L)) 
w=np.sin([4,5,6]) ;print(w) ; print(type(w))

On peut concaténer deux listes numériques avec np.append: le résultat est un tableau numpy

In [ ]:
v = np.append([4, 5, 6], [22, 25]); print(v); print(type(v))

On peut convertir une liste en tableau numpy en utilisant np.array

In [ ]:
tL = np.array(L); type(tL)

## Attention ! Les objets de type numpy array sont mutables

In [ ]:
t = np.array([1, 2, 3])  
v=t
t[0]=7
t.sort()
print(t)
print(v)  
id(v)==id(t) 

In [ ]:
t = np.array([1, 2, 3])  
v=np.copy(t) 
# v=1*t # alternative 1
# v=t.copy() # alternative 2
t[0]=7
t.sort()
print(t)
print(v)  
id(v)==id(t) 

## Exemples de fonctions pouvant s'appliquer à des tableaux numpy

In [ ]:
# my_mean1 et my_mean2 peuvent s'appliquer à un tableau numpy, une liste ou à un tuple
def my_mean1(a):                                                                
    return 1.*sum(a)/len(a)                                                     
                                                                                
def my_mean2(a):                                                                
    s = 0.                                                                      
    for i in np.arange(len(a)):                                                 
        s = s + a[i]                                                            
    return 1.*s/len(a)

l = [120, 12, -2, 17, 15]
print([my_mean1(l), my_mean2(l), np.mean(l)]) 
A = np.array(l)                                             
print([my_mean1(A), my_mean2(A), np.mean(A)]) 
t = tuple(l)
print([my_mean1(t), my_mean2(t), np.mean(t)]) 